[environments]

[environments.default]
store = "kpdtdw-1m.myshopify.com"
ignore = ["*.tmp", "*.bak", "*.swp", "*.swo", "*~", ".DS_Store", "Thumbs.db", "node_modules/**", ".tmp/**", "tmp/**", ".qwen/**", ".claude/**", ".cursor/**", "Session/**", "TEAM-WORK/**", ".git/**", "test-results/**"]
